project_id = "idvwckpcsktnplnvwvba"

[functions.bulk-import-colleges]
verify_jwt = true

[functions.send-email-verification]
verify_jwt = true

[functions.verify-email-code]
verify_jwt = true

[functions.sitemap]
verify_jwt = false
